### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by davidlukac** [slovak-drupal-association/HostingTest#15]
Use the Slider from #4  and Latest News from #3 .

Create script for generating content for all content types that are displayed on the homepage:
- [x] Article
- [x] Event
- [x] Forum topic (generate many comments)
- [x] News

Other tasks:
- [x] create install/re-install script
- [x] set up path auto
- [x] fix permissions, so anonymous user can see the homepage
  - [x] fix forum permissions - should be seen by anonymous

**Comment by miromichalicka** [comment]
Use also Block from #6.
