### ISSUE TITLE
Create Content types

### ISSUE THREAD

**Issue by miromichalicka** [slovak-drupal-association/HostingTest#2]
- [x] Article with Paragraphs
  - Title
  - Paragraphs
    - [x] Text Paragraph 
    - [x] Image Paragraph
    - [x] Image + Text Paragraph 
    - [x] Image + Image Paragraph
  - Category
- [x] News
  - Title
  - Text
  - Image
  - Category
- [x] Forum
  - use core Drupal module
- [x] Event
  - only for authenticated users
  - Title
  - Text
  - Image
  - Location

**Comment by davidlukac** [comment]
Entity reference as `Category` field allows only tagging w/ existing tags, so these will have to be created before importing the testing content (#12).

**Comment by davidlukac** [comment]
Resolved, closing.
